export const GET_COMPONENTS = 'GET_COMPONENTS';
export const CHANGE_POSITION = 'CHANGE_POSITION';
export const CHANGE_POSITION_T = 'CHANGE_POSITION_T';
export const CHANGE_POSITION_A = 'CHANGE_POSITION_A';
export const CHANGE_ROTATE = 'CHANGE_ROTATE';
export const SET_COMPONENTS = 'SET_COMPONENTS';
export const GET_TEMPLATES = 'GET_TEMPLATES';
export const POST_TEMPLATES = 'POST_TEMPLATES';
export const POST_TEXT_TEMPLATES = 'POST_TEXT_TEMPLATES';
export const FILTRAR_TEMPLATES = 'FILTRAR_TEMPLATES';
export const FILTRAR_COMPONENTES_IEC = 'FILTRAR_COMPONENTES_IEC';
export const FILTRAR_COMPONENTES_ANSI = 'FILTRAR_COMPONENTES_ANSI';
export const FILTRAR_COMPONENTES_UNIONES = 'FILTRAR_COMPONENTES_UNIONES';
export const FILTRAR_COMPONENTES_OTROS = 'FILTRAR_COMPONENTES_OTROS';
export const GET_TEMPLATE = 'GET_TEMPLATE';
export const CLOSE_TEMPLATE = 'CLOSE_TEMPLATE';
export const GET_TEMPLATE_ID = 'GET_TEMPLATE_ID';
export const TEMPLATE_ACTUAL = 'TEMPLATE_ACTUAL';

export const SET_TRANSLATEX = 'SET_TRANSLATEX';
export const GET_TRANSLATEX = 'GET_TRANSLATEX';
export const SET_TRANSLATEY = 'SET_TRANSLATEY';
export const GET_TRANSLATEY = 'GET_TRANSLATEY';


export const AUTH_USER = "AUTH_USER";
export const ERROR_REMOVE = "ERROR_REMOVE";
export const ADD_ERROR = "ADD_ERROR";
export const LOGOUT_USER  = "LOGOUT_USER";
export const NOT_AUTHENTICATED = "NOT_AUTHENTICATED";

export const SYNCRONIZE = "SYNCRONIZE";