const images = ["Group_01_icono.svg",
    "Group_02_icono.svg",
    "Group_03_icono.svg",
    "Group_04_icono.svg",
    "Group_05_icono.svg",
    "Group_06_icono.svg",
    "Group_07_icono.svg",
    "Group_08_icono.svg",
    "Group_09_icono.svg",
    "Group_10_icono.svg",
    "Group_11_icono.svg",
    "Group_12_icono.svg",
    "Group_13_icono.svg",
    "Group_14_icono.svg",
    "Group_15_icono.svg",
    "Group_16_icono.svg",
    "Group_17_icono.svg",
    "Group_116_icono.svg"];

export default images;